import React from 'react';
import type { Metadata } from "next";
import Footer from './footer';
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>Handcrafted-Haven</title>
      </head>
      <body>
        <div className="container">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default Layout;


// import type { Metadata } from "next";
// import Footer from './footer';
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx
// src/app/layout.tsx

